feat: endpoint-worker
edu2andrade/booking-manager-system pull request #14
Opened 2023-04-30 16:05 UTC by RonaldoDairo

2023-04-30 16:17 UTC, rlence requested changes

2023-04-30 16:17 UTC, rlence commented on src/api/domain/workers/controller.py
> +    if worker_id is None:
Este if no tiene sentido

2023-04-30 16:17 UTC, rlence commented on src/api/domain/workers/repository.py
> +    all_workers = Workers.query.all()
Esto esta mal, no es buscar todos los trabajadores es para buscar todos los trabajadores de una company en concreto

2023-04-30 16:17 UTC, rlence commented on src/api/domain/workers/route.py
> +@api.route("/all", methods=["GET"])
Se tendrá que pasar el company_id

2023-04-30 16:17 UTC, rlence commented on src/api/domain/workers/route.py
> +def delete_worker(id):
Esta ruts debe estar protegida por token

2023-04-30 16:17 UTC, rlence commented on src/api/domain/workers/controller.py
> +def get_worker_list():
Se debería de pasar el company_id para buscar trabajadores por el id de una company

2023-04-30 19:32 UTC, RonaldoDairo commented on src/api/domain/workers/controller.py
> +    if worker_id is None:
lo he quitado

2023-04-30 19:36 UTC, RonaldoDairo commented on src/api/domain/workers/controller.py
> +def get_worker_list():
esto creo que ya estaba resuelto , he hecho algunas modificacion en repository

2023-04-30 19:37 UTC, RonaldoDairo commented on src/api/domain/workers/route.py
> +def delete_worker(id):
ya esta protegida , al intentar eliminar me dice   "msg": "Missing Authorization Header"

2023-04-30 19:39 UTC, RonaldoDairo commented on src/api/domain/workers/route.py
> +@api.route("/all", methods=["GET"])
esta creo que esta hecha ya , es el siguiente endpoint .

2023-04-30 19:41 UTC, RonaldoDairo commented on src/api/domain/workers/repository.py
> +    all_workers = Workers.query.all()
He cambiado , Workers a Company , la verdad no entiendo lo que me has querido decir aqui .

2023-05-01 07:05 UTC, rlence approved these changes

2023-05-01 17:28 UTC, merged