Feature/service endpoints
edu2andrade/booking-manager-system pull request #16
Opened 2023-05-03 10:18 UTC by edu2andrade

2023-05-03 13:25 UTC, rlence requested changes

2023-05-03 13:30 UTC, edu2andrade commented on src/api/domain/services/controller.py
> +    user_id = Company.query.get(service_company_id).user_id
Vale, y cómo lo solucionamos?

2023-05-03 13:56 UTC, edu2andrade commented on src/api/domain/services/controller.py
> +    user_id = Company.query.get(service_company_id).user_id
Espera, no existe un service sin un company_id asociado. Es obligatorio al crear un service, luego, si existe un service, existe una company asociada a este service. Cuando haces un delete de una company, también haces delete de todos los services asociados a esta, debería hacer delete también de los workers, clients, etc.

2023-05-04 17:18 UTC, rlence approved these changes

2023-05-05 07:53 UTC, merged