Endpoint worker
edu2andrade/booking-manager-system pull request #17
Opened 2023-05-03 13:51 UTC by RonaldoDairo

2023-05-03 18:12 UTC, rlence requested changes

2023-05-03 18:12 UTC, rlence commented on src/api/domain/workers/route.py
> +    user_id = worker.user_id
esto que es? que estas haciendo aqui?

2023-05-03 18:38 UTC, RonaldoDairo commented on src/api/domain/workers/route.py
> +    if current_worker_id != user_id:
@api.route("/<int:worker_id>", methods=["DELETE"])
@jwt_required()
def delete_worker(worker_id):
    current_worker = get_jwt_identity()
    current_worker_id = current_worker["id"]
    print("Current_worker_id++++++++++++", current_worker_id)
    print("Current_workers++++++++++++", current_worker)
    worker = Workers.query.get(worker_id)

    if worker is None:
        return Response.response_error("Worker is not found", 400)

    company = worker.company
    user_id = company.user_id
    print("user_id", user_id)
    if current_worker_id != user_id:
        return Response.response_error(
            "You do not have permission to delete this worker", 401
        )

    eliminated = Controller.delete_worker(worker_id)
    if eliminated:
        return Response.response_ok(
            f"Worker with id: {worker_id} has been deleted", 200
        )
    else:
        return Response.response_error(
            f"Error deleting worker with id: {worker_id}", 500
        ) es como debe ser ?

2023-05-05 05:57 UTC, rlence approved these changes

2023-05-05 10:19 UTC, merged