Endpoint service workers
edu2andrade/booking-manager-system pull request #20
Opened 2023-05-06 20:19 UTC by RonaldoDairo

2023-05-07 09:02 UTC, rlence requested changes

2023-05-07 09:02 UTC, rlence commented on src/api/domain/service_worker/controller.py
> +        return Repository.create_new_service(body, service_id, worker_id)
porque creas un servicio no tiens que crear un servicio para esto y te falta hacer la comprobacion de la company ande de crear el service_worker

2023-05-07 09:02 UTC, rlence commented on src/api/domain/service_worker/controller.py
> +    if Repository.delete_service_worker(service_id):
hay que hacer la validaciones para esto

2023-05-07 09:02 UTC, rlence commented on src/api/domain/service_worker/repository.py
> +    serialize_all_servicesWorkers = list(
serialize en la ruta, y hay que buscar los services worker por company id, y por worker_id

2023-05-07 12:32 UTC, RonaldoDairo commented on src/api/domain/service_worker/controller.py
> +        return Repository.create_new_service(body, service_id, worker_id)
esta hecho

2023-05-07 12:32 UTC, RonaldoDairo commented on src/api/domain/service_worker/controller.py
> +    if Repository.delete_service_worker(service_id):
he puesto unas mas validaciones

2023-05-07 12:48 UTC, RonaldoDairo commented on src/api/domain/service_worker/repository.py
> +    serialize_all_servicesWorkers = list(
Hecho el end point para buscar services worker por company id y otro end point para buscar por id del worker id ...Lo que no encuentro es poder serializar en la rotes con los get , y los compañeros aun tampoco lo han logrado hacer

2023-05-08 13:15 UTC, rlence commented on src/api/domain/service_worker/controller.py
> +def get_all_servicesWorkers():
este enpoint no te hace falta

2023-05-08 13:15 UTC, rlence commented on src/api/domain/service_worker/controller.py
> +    if Repository.delete_service_worker(service_id):
pero solo las veo en el create, en el delete no las veo

2023-05-08 13:15 UTC, rlence commented on src/api/domain/service_worker/route.py
> +def get_all_servicesWorkers():
esto no haria falta

2023-05-10 20:01 UTC, rlence approved these changes

2023-05-10 21:45 UTC, merged