Fix details update profile
edu2andrade/booking-manager-system pull request #64
Opened 2023-06-09 16:06 UTC by RonaldoDairo

2023-06-10 04:39 UTC, edu2andrade requested changes
Además de lo comentado te faltan:

- las validaciones, 
- y como te he dicho, pones una foto (un print de tu pantalla) de tu componente listo para que tengamos idea de como está, yo todavía no consigo imaginar como queda con tan sólo mirar CSS 😅

2023-06-10 04:39 UTC, edu2andrade commented on src/front/js/pages/profile/index.jsx
> +
Cuando el user hace el update de su perfil tiene que ser redireccionado para su ***Dashboard***, no para el login, y no le quites el token, en este caso no ha hecho ***sign out***, no tiene sentido.

Las validaciones en el form?

2023-06-10 23:08 UTC, RonaldoDairo commented on src/front/js/pages/profile/index.jsx
> +
Le he quitado el token porque le doy para atras o le profile/1 puedes cambiar facilmente , en cambio si elimino el token no puede actualizarlo de esa manera

2023-06-11 17:12 UTC, edu2andrade requested changes
<img width="1466" alt="Screenshot 2023-06-11 at 19 03 48" src="https://github.com/edu2andrade/booking-manager-system/assets/90911179/db45e88c-ffbf-4721-8885-19b50b3922cb">

- Yo le veo así en mi local.
- Como ves, se me ha quitado la foto de perfil que tenía al actualizar sin poner una nueva

2023-06-11 17:12 UTC, edu2andrade commented on src/api/domain/users/controller.py
> +    url_avatar = None
Cuando el avatar que viene del route es None, esa linea pasa el url_avatar a None también, o sea le quita la foto que el user ya tiene si él no sube otra. Hay que hacer otro tipo de comprobación por aquí o por el route, para que funcione correctamente.

2023-06-11 17:12 UTC, edu2andrade commented on src/front/js/pages/profile/index.jsx
> +
Aquí sacas el role_id del localStorage (por eso te he dicho para no quitar el token) y redirecciona para el dashboard que le toca, tienes un ejemplo de como se hace en el header.

2023-06-11 17:14 UTC, edu2andrade requested changes
Borra todos los console.log que has puesto para probar, incluso los que ya tenía en el context

2023-06-11 18:18 UTC, RonaldoDairo commented on src/api/domain/users/controller.py
> +    url_avatar = None
no entiendo porque te aparece así , también te aparece mas alineado

2023-06-12 20:36 UTC, merged